name: 415-Cradle/Cradle-SMSRelay
# Main GitHub CI/CD pipeline definition file
# For syntax, see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
env: 
    CUSTOM_WORKSPACE: /isolated-build/repo

jobs:
  display_github_contexts:
    name: Display github Contexts
    runs-on: [self-hosted, docker]
    container: 
      image: node:14
    steps:
      - uses: bfraser/cicd/actions/debug_display_contexts@v1

  static_analysis:
    name: Code Analysis
    runs-on: [self-hosted, docker]
    container: 
      image: cangol/android-gradle
    steps:
      - name: Checkout repository into Container
        uses: bfraser/cicd/actions/checkout@v1
        with: 
          path: ${{ env.CUSTOM_WORKSPACE }}
      - name: Run static code analysis 
        run: ./gradlew detekt
        working-directory: ${{ env.CUSTOM_WORKSPACE }}
  
  build:
    name: Build and Asemble Debug APK
    runs-on: [self-hosted, docker]
    container: 
      image: cangol/android-gradle
    steps:
      - name: Checkout repository into Container
        uses: bfraser/cicd/actions/checkout@v1
        with: 
          path: ${{ env.CUSTOM_WORKSPACE }}
      - name: Assemble Debug APK
        run: ./gradlew assembleDebug
        working-directory: ${{ env.CUSTOM_WORKSPACE }}
  
  test:
    name: Run Local Unit Tests
    runs-on: [self-hosted, docker]
    container: 
      image: cangol/android-gradle
    needs: [ build ]
    steps:
      - name: Checkout repository into Container
        uses: bfraser/cicd/actions/checkout@v1
        with: 
          path: ${{ env.CUSTOM_WORKSPACE }}
      - name:  Run Local Unit Tests
        run: ./gradlew test
        working-directory: ${{ env.CUSTOM_WORKSPACE }}
    
    



