name: 415-Cradle/Cradle-SMSRelay
# Main GitHub CI/CD pipeline definition file
# For syntax, see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
env: 
    CUSTOM_WORKSPACE: /isolated-build/repo

jobs:
  display_github_contexts:
    name: Display github Contexts
    runs-on: [self-hosted, docker]
    container: 
      image: node:14
    steps:
      - name: Display commonly used info
        run: |
          echo "  CI/CD Event Name  = ${{ github.event_name }}"
          echo "  PR request Number = ${{ github.event.pull_request.number }}"
          echo "  Refspec           = ${{ github.ref }}"
          echo "  Branch name       = ${{ github.ref_name }}"
          echo "  Commit SHA        = ${{ github.sha }}"
      - name: Dump GitHub context
        env:
           GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo '$STEPS_CONTEXT'
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo '$RUNNER_CONTEXT'
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo '$STRATEGY_CONTEXT'
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  static_analysis:
    name: Code Analysis
    runs-on: [self-hosted, docker]
    container: 
      image: cangol/android-gradle
    steps:
      - name: Checkout repository into Container
        uses: bfraser/cicd/actions/checkout@v1
        with: 
          path: ${{ env.CUSTOM_WORKSPACE }}
      - name: Run static code analysis 
        run: ./gradlew detekt
        working-directory: ${{ env.CUSTOM_WORKSPACE }}
  
  build:
    name: Build and Asemble Debug APK
    runs-on: [self-hosted, docker]
    container: 
      image: cangol/android-gradle
    steps:
      - name: Checkout repository into Container
        uses: bfraser/cicd/actions/checkout@v1
        with: 
          path: ${{ env.CUSTOM_WORKSPACE }}
      - name: Assemble Debug APK
        run: ./gradlew assembleDebug
        working-directory: ${{ env.CUSTOM_WORKSPACE }}
  
  test:
    name: Run Local Unit Tests
    runs-on: [self-hosted, docker]
    container: 
      image: cangol/android-gradle
    needs: [ build ]
    steps:
      - name: Checkout repository into Container
        uses: bfraser/cicd/actions/checkout@v1
        with: 
          path: ${{ env.CUSTOM_WORKSPACE }}
      - name:  Run Local Unit Tests
        run: ./gradlew test
        working-directory: ${{ env.CUSTOM_WORKSPACE }}
    
    



